### ISSUE TITLE
Balance value on the web page won't refresh sometimes after deposit

### ISSUE THREAD

**Issue by EthanYuan** [RetricSu/godwoken-kicker#11]
Balance value on the web page won't refresh sometimes after deposit.
At this time, close the browser, re-start and load the page, the balance update.

**Comment by RetricSu** [comment]
when the l1 deposit tx is on chain, the deposit is successfully done. but balance is gained only after godwoken produce the new block including this new deposit cell. the getBalance rpc method will add a  block parameter recently, should be able to fixed this issue after apply block parameter when request for quering balance.

**Comment by RetricSu** [comment]
metamask eth balance is 0, that's normal. because we deposit 400 ckb on your account each time. due to the decimal difference in ckb and eth(one is 8, the other is 18), the coverting eth balance is too small to display. but on your page, the ckb balance should be 400 ckb. somehow the balance here is not updating, i will take a quick look.

**Comment by RetricSu** [comment]
should be a godwoken-web3 env problem when starting for the first time. 

I guess restarting the godwoken-web3 service in docker  will solve the problem. 

```sh
make stop-web3
make start-web3
```

or you can just try with newest mater branch. 

the issue should be fixed with this commit. https://github.com/RetricSu/godwoken-kicker/commit/51dadd129fee65e23446b3a44c1b90417837c70b
