### ISSUE TITLE
manual-build bugs

### ISSUE THREAD

**Issue by classicalliu** [RetricSu/godwoken-kicker#197]
compatibility-changes branch

1. Created dir `docker/manual-artifacts` is owned by root, so it will throw `Permission denied` error when create file / dir.
2. `docker/manual-artifacts/gw-tools` is an empty dir, not a bin, so it will throw error when run `./kicker start`.
3. `docker/manual-artifacts/godwoken-web3` will start without build, so web3 service will not work, should run `yarn run build` manually.

**Comment by keroro520** [comment]
> compatibility-changes branch
> 
> 1. Created dir `docker/manual-artifacts` is owned by root, so it will throw `Permission denied` error when create file / dir.
> 2. `docker/manual-artifacts/gw-tools` is an empty dir, not a bin, so it will throw error when run `./kicker start`.
> 3. `docker/manual-artifacts/godwoken-web3` will start without build, so web3 service will not work, should run `yarn run build` manually.

Well, I am will try to explain these issues and plan what should we do about these issues:

1. `docker/manual-artifacts` is supposed to be created when the user executes `./kicker manual-build`(type`grep 'mkdir -p' kicker` for more detail). However, it can also be created by docker-compose voluming directory, which I guess is the case what @classicalliu encountered. This is something we need to consider.

  - [ ] create `docker/manual-artifacts` directory at `kicker start`. So that the directory is owned by the current user but not docker/root.
  - [ ] remove `docker/manual-artifacts` directory at `kicker clean`

2. Similar issue to 1.

  * [ ] Before starting Docker-Compose services, Kicker should check that the manual artifacts exist.

3. Similar issue to 2
